import { chromium, expect } from '@playwright/test';
import QRCode from 'qrcode';
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{})});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1080}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:5173');
 await page.getByRole('button',{name:'Try demo',exact:true}).click();
 await page.screenshot({path:'/private/tmp/dibi-desktop.png',fullPage:true});
 await expect(page.locator('.count')).toContainText('42');
 await page.getByRole('button',{name:'Valid ticket',exact:false}).click();
 await expect(page.getByRole('heading',{name:'You’re in. Welcome!'})).toBeVisible();
 await page.getByRole('button',{name:'Scan next guest'}).click();
 await expect(page.locator('.count')).toContainText('43');
 await page.getByRole('button',{name:'Already checked in',exact:false}).click();
 await expect(page.getByRole('heading',{name:'Already checked in'})).toBeVisible();
 await page.getByRole('button',{name:'Send to help queue'}).click();
 await page.getByRole('button',{name:'Unknown ticket',exact:false}).click();
 await expect(page.getByRole('heading',{name:'Ticket not found'})).toBeVisible();
 await page.getByRole('button',{name:'Send to help queue'}).click();
 await page.locator('nav').getByRole('button',{name:/Help queue/}).click();
 await expect(page.locator('.queue-row')).toHaveCount(2);
 await page.getByRole('button',{name:'Review'}).first().click();
 await page.getByRole('button',{name:'Mark issue resolved'}).click();
 await expect(page.locator('.queue-row')).toHaveCount(1);
 await page.locator('nav').getByRole('button',{name:'Attendees',exact:true}).click();
 await page.getByRole('searchbox').fill('Priya Patel');
 await expect(page.locator('tbody tr')).toHaveCount(1);
 await page.getByRole('button',{name:'Check in',exact:false}).click();
 await page.getByRole('button',{name:'Confirm check-in'}).click();
 await expect(page.getByRole('heading',{name:'You’re in. Welcome!'})).toBeVisible();
 await page.getByRole('button',{name:'Scan next guest'}).click();
 await page.reload();
 await page.getByRole('button',{name:'Try demo',exact:true}).click();
 await expect(page.locator('.count')).toContainText('44');
 await page.getByRole('button',{name:'Enter ticket code'}).click();
 await page.getByLabel('Ticket code',{exact:true}).fill('DIBI-0002');
 await page.getByRole('button',{name:'Check ticket',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Already checked in'})).toBeVisible();
 await page.getByRole('button',{name:'Try another ticket'}).click();
 await QRCode.toFile('/private/tmp/dibi-test-qr.png','DIBI-0003',{width:400});
 await page.locator('#qr-upload').setInputFiles('/private/tmp/dibi-test-qr.png');
 await expect(page.getByRole('heading',{name:'You’re in. Welcome!'})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Jamie Chen',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Scan next guest'}).click();
 await page.getByRole('button',{name:'Show sample QR tickets'}).click();
 await expect(page.locator('.sample img')).toHaveCount(3);
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Enter ticket code'}).click();
 await page.getByLabel('Ticket code',{exact:true}).fill('DEMO-EB-001');
 await page.getByRole('button',{name:'Check ticket',exact:true}).click();
 await expect(page.getByRole('heading',{name:'You’re in. Welcome!'})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Ticket 1',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Scan next guest'}).click();
 await page.getByRole('button',{name:'Register existing QR',exact:true}).click();
 await page.getByLabel('QR text or URL',{exact:true}).fill('https://event.example/SharedLink');
 await page.getByRole('button',{name:'Continue',exact:false}).click();
 await page.getByLabel('How is this QR used?').selectOption('shared');
 await page.getByRole('button',{name:'Register & find guest'}).click();
 await expect(page.getByRole('heading',{name:'Let’s find your guest.'})).toBeVisible();
 await expect(page.locator('.count')).toContainText('46');
 await page.getByLabel('Individual ticket code',{exact:true}).fill('DEMO-EB-002');
 await page.getByRole('button',{name:'Check ticket',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Ticket 2',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Scan next guest'}).click();
 await page.getByRole('button',{name:'Register existing QR',exact:true}).click();
 await page.getByLabel('QR text or URL',{exact:true}).fill('https://tickets.example/AbC123');
 await page.getByRole('button',{name:'Continue',exact:false}).click();
 await page.getByLabel('Guest record',{exact:true}).selectOption('new');
 await page.getByLabel('Full name',{exact:true}).fill('Existing QR Guest');
 await page.getByRole('button',{name:'Register for later'}).click();
 await expect(page.locator('.count')).toContainText('47');
 await page.reload();
 await page.getByRole('button',{name:'Try demo',exact:true}).click();
 await page.getByRole('button',{name:'Enter ticket code'}).click();
 await page.getByLabel('Ticket code',{exact:true}).fill('https://tickets.example/AbC123');
 await page.getByRole('button',{name:'Check ticket',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Existing QR Guest',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Scan next guest'}).click();
 await page.getByRole('button',{name:'Open camera'}).click();
 await expect(page.locator('.camera-error')).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/private/tmp/dibi-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 expect(errors).toEqual([]);
 console.log('PASS: success, duplicate prevention, unknown tickets, queue resolution, search, manual check-in, persistence, real QR decoding, sample tickets, camera fallback, mobile overflow, no JS errors.');
}finally{await browser.close()}
