import {chromium,expect} from '@playwright/test';
import QRCode from 'qrcode';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{})});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1080}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const enterCode=async code=>{await page.getByRole('button',{name:'Enter ticket code'}).click();await page.getByLabel('Ticket code',{exact:true}).fill(code);await page.getByRole('button',{name:'Check ticket',exact:true}).click()};
 await page.goto('http://localhost:5173');
 await expect(page.locator('.workspace-bar')).toContainText('Staff check-in');
 await expect(page.locator('.count')).toHaveText('0 / 300');
 await expect(page.locator('[data-demo]')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Register existing QR',exact:true})).toHaveCount(0);
 await page.screenshot({path:'/private/tmp/dibi-scanning-desktop.png',fullPage:true});
 await QRCode.toFile('/private/tmp/dibi-ticket-qr.png','DEMO-EB-001',{width:400});
 await page.locator('#qr-upload').setInputFiles('/private/tmp/dibi-ticket-qr.png');
 await expect(page.getByRole('heading',{name:'Ticket scanned',exact:true})).toBeVisible();
 await expect(page.locator('.scan-receipt')).toContainText('DEMO-EB-001');
 await expect(page.locator('#modal input')).toHaveCount(0);
 await expect(page.locator('.count')).toHaveText('1 / 300');
 await page.screenshot({path:'/private/tmp/dibi-scan-success.png'});
 await page.getByRole('button',{name:'Scan next ticket',exact:true}).click();
 await enterCode('DEMO-EB-001');
 await expect(page.getByRole('heading',{name:'Already scanned',exact:true})).toBeVisible();
 await expect(page.locator('.count')).toHaveText('1 / 300');
 await page.getByRole('button',{name:'Send to help queue'}).click();
 await page.locator('nav').getByRole('button',{name:/Help queue/}).click();
 await expect(page.locator('.queue-row')).toHaveCount(1);
 await page.locator('nav').getByRole('button',{name:'Check-in',exact:true}).click();
 await enterCode('DEMO-EB-002');
 await expect(page.getByRole('heading',{name:'Ticket scanned',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Scan next ticket',exact:true}).click();
 await enterCode('A-new-supplied-ticket');
 await expect(page.getByRole('heading',{name:'Ticket scanned',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Scan next ticket',exact:true}).click();
 await expect(page.locator('.count')).toHaveText('3 / 300');
 await page.getByRole('button',{name:'Try demo',exact:true}).click();
 await expect(page.locator('.count')).toContainText('42');
 await page.getByRole('button',{name:'Valid ticket',exact:false}).click();
 await page.getByRole('button',{name:'Scan next guest'}).click();
 await page.getByRole('button',{name:'Back to desk',exact:true}).click();
 await expect(page.locator('.count')).toHaveText('3 / 300');
 await page.reload();
 await expect(page.locator('.count')).toHaveText('3 / 300');
 await enterCode('DEMO-EB-001');
 await expect(page.getByRole('heading',{name:'Already scanned',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Scan next ticket',exact:true}).click();
 await page.locator('nav').getByRole('button',{name:'Scan log',exact:true}).click();
 await expect(page.locator('tbody tr')).toHaveCount(3);
 await page.getByRole('searchbox').fill('DEMO-EB-001');
 await expect(page.locator('tbody tr')).toHaveCount(1);
 await page.getByRole('button',{name:'View ticket'}).click();
 await expect(page.locator('.scan-receipt')).toContainText('DEMO-EB-001');
 await page.getByRole('button',{name:'Add guest details (optional)'}).click();
 await expect(page.locator('#desk-name')).toHaveValue('');
 await page.locator('#desk-name').fill('Optional Name');
 await page.getByRole('button',{name:'Save details',exact:true}).click();
 await expect(page.locator('tbody')).toContainText('Optional Name');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export'}).click();
 const download=await downloadPromise;const csv=await fs.readFile(await download.path(),'utf8');
 expect(download.suggestedFilename()).toBe('dibi-ticket-scans.csv');expect(csv).toContain('DEMO-EB-001');expect(csv).toContain('DEMO-EB-002');expect(csv).not.toContain('Alex Morgan');
 await page.locator('nav').getByRole('button',{name:'Check-in',exact:true}).click();
 await enterCode('DEMO-EB-001');await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/private/tmp/dibi-scan-duplicate-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
 console.log('PASS: QR image records immediately, no details form, unique codes counted once, duplicates persist after refresh, duplicate queue, demo isolation, searchable scan log, export, optional details and mobile layout.');
}finally{await browser.close()}
