import './style.css';
import './brand.css';
import jsQR from 'jsqr';
import QRCode from 'qrcode';
import {createState,checkIn,addToQueue,findAttendee,registerQR,registerSharedQR,createDeskState,updateGuestDetails,recordTicketScan} from './store.js';
const icons={scan:'<rect x="7" y="7" width="4" height="4"/><rect x="14" y="7" width="3" height="3"/><rect x="7" y="14" width="3" height="3"/><path d="M14 14h3v3h-3M3 8V3h5m8 0h5v5M3 16v5h5m8 0h5v-5"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-17a3 3 0 0 1 0 6m3 11v-3a6 6 0 0 0-2-4"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4m0 3h.01"/>',camera:'<path d="M3 7h4l2-3h6l2 3h4v13H3z"/><circle cx="12" cy="13" r="4"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',warning:'<path d="m12 3 10 18H2zM12 9v5m0 3h.01"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',upload:'<path d="M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.scan}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readSaved(key){try{return JSON.parse(localStorage.getItem(key))}catch{return null}}
const legacy=readSaved('dibi-demo-v1');
let workspace='desk';
let demoState=legacy?.version===1&&Array.isArray(legacy.attendees)?legacy:createState();
for(const [code,name] of [['DEMO-EB-001','Ticket 1'],['DEMO-EB-002','Ticket 2']]) {
 if(!findAttendee(demoState,code)) registerQR(demoState,code,{name,company:'Provided event ticket'}).type='Early Bird';
}
const savedDesk=readSaved('dibi-desk-v2');
let deskState=savedDesk?.version===2&&Array.isArray(savedDesk.attendees)?savedDesk:createDeskState(legacy);
let state=deskState;
let view='checkin', filter='all', search='', result=null, stream=null, frame=null, cameraGeneration=0, previousFocus=null, registering=false;
const $=s=>document.querySelector(s);
const time=t=>new Date(t).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
function save(){try{localStorage.setItem(workspace==='desk'?'dibi-desk-v2':'dibi-demo-v1',JSON.stringify(state))}catch{toast('Browser storage unavailable. Keep this tab open to retain check-ins.')}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4000)}
function render(){
 const count=state.attendees.filter(a=>a.checkedIn).length;
 const total=workspace==='desk'?Math.max(state.target||300,count):Math.max(state.attendees.length,1);
 $('#app').innerHTML=`
 <header class="header">
  <a class="brand" href="#" aria-label="DiBi check-in home"><img src="/dibi-mark.svg" alt="DiBi" width="107" height="47"></a>
  <div class="event-date">30th Sept & 1st Oct 2026<br><span>Edinburgh, Scotland</span></div>
  <nav aria-label="Main navigation">${[['checkin','Check-in'],['attendees',workspace==='desk'?'Scan log':'Attendees'],['queue','Help queue']].map(([v,label])=>`<button class="nav-item ${view===v?'active':''}" data-view="${v}" ${view===v?'aria-current="page"':''}>${label}${v==='queue'&&state.queue.length?`<span class="nav-count">${state.queue.length}</span>`:''}</button>`).join('')}</nav>
 </header>
 <main>
  <div class="workspace-bar"><span>${workspace==='desk'?'Staff check-in':'Demo mode · Sample data'}</span>${workspace==='demo'?'<span>Practice scans are separate from the desk log.</span>':''}</div>
  <section class="intro">
   <div><h1>${view==='checkin'?'Check-in.':view==='attendees'?(workspace==='desk'?'Scan log.':'Attendees.'):'Help queue.'}</h1><p>${view==='checkin'?'Scan each ticket once.':view==='attendees'?'Search or export the tickets recorded on this device.':'Review tickets that need attention.'}</p></div>
   <div class="progress-summary"><div class="count">${count}<span> / ${total}</span></div><span class="count-caption">tickets scanned</span><div class="progress-track" role="progressbar" aria-label="Tickets scanned" aria-valuenow="${count}" aria-valuemin="0" aria-valuemax="${total}"><div style="width:${count/total*100}%"></div></div></div>
  </section>
  ${view==='checkin'?checkinView():view==='attendees'?attendeesView():queueView()}
  <footer><span>${workspace==='desk'?'Scan log saved on this device':'Demo data · Saved separately'}</span><button class="text-btn" id="switch-workspace">${workspace==='desk'?'Try demo':'Back to desk'} ${icon('arrow')}</button></footer>
 </main><dialog id="modal"></dialog><div id="toast" role="status"></div><input type="file" id="qr-upload" accept="image/*" hidden>`;
 bind();
 $('#switch-workspace').onclick=()=>{stopCamera();save();workspace=workspace==='desk'?'demo':'desk';state=workspace==='desk'?deskState:demoState;view='checkin';search='';filter='all';registering=false;render()};
}
function checkinView(){
 const activity=state.activity.slice(0,5);
 return `<section class="dashboard">
  <article class="scan-card">
   <div class="card-heading"><h2>Scan a ticket</h2><span class="subtle">QR check-in</span></div>
   <div class="scanner" id="scanner">
    <div class="scanner-top"><span id="camera-status">Camera off</span>${icon('camera')}</div>
    <video id="camera" playsinline muted hidden></video><div class="live-scan-frame" aria-hidden="true"></div>
    <div class="scanner-content" id="scanner-content"><div class="scan-frame" aria-hidden="true"><i></i><i></i><i></i><i></i>${icon('scan')}</div><h3>Ready to scan</h3><button class="btn lime" id="start-camera">Open camera ${icon('arrow')}</button></div>
    <button class="camera-stop" id="stop-camera" hidden>Stop camera</button><span class="scanner-foot">Hold the ticket’s QR code inside the frame.</span>
   </div>
   <div id="camera-message" role="status"></div>
   <div class="scan-tools"><button class="text-btn" id="upload-btn">${icon('upload')}Upload QR image</button><button class="text-btn" id="manual-btn">Enter ticket code ${icon('arrow')}</button></div>
   ${workspace==='demo'?`<div class="register-existing"><span>Link a ticket to a sample guest.</span><button class="text-btn" id="register-existing">Register existing QR ${icon('arrow')}</button></div>`:''}
  </article>
  <aside class="activity-card">
   <div class="card-heading"><h2>Recent scans</h2><span class="subtle">${activity.length?Math.min(5,state.activity.length)+' latest':'This device'}</span></div>
   <div class="activity-list">${activity.length?activity.map(a=>{const ticket=state.attendees.find(t=>t.id===a.id);const label=workspace==='desk'?(ticket?.qrCodes?.[0]||a.name):a.name;return `<div class="activity-row"><span class="activity-check">${icon('check')}</span><div class="activity-person"><strong>${esc(label)}</strong><span>${workspace==='desk'?'Scanned':esc(a.method)}</span></div><time datetime="${esc(a.time)}">${time(a.time)}</time></div>`}).join(''):'<div class="activity-empty"><span class="empty-dash">—</span><h3>No scans yet.</h3><p>Scanned ticket codes will appear here.</p></div>'}</div>
   <button class="text-btn all-attendees" data-view="attendees">${workspace==='desk'?'View scan log':'View all attendees'} ${icon('arrow')}</button>
   <div class="staff-tip"><p>Ticket already scanned?</p><button class="text-btn" data-view="queue">Open help queue ${icon('arrow')}</button></div>
  </aside>
 </section>
 ${workspace==='demo'?`<section class="demo-bar"><div class="demo-label"><strong>Test tickets</strong><span>Sample data only</span></div><div class="demo-actions"><button data-demo="success">Valid ticket ${icon('arrow')}</button><button data-demo="duplicate">Already checked in ${icon('arrow')}</button><button data-demo="unknown">Unknown ticket ${icon('arrow')}</button></div><button class="ticket-link" id="sample-tickets" aria-label="Show sample QR tickets">${icon('scan')}</button></section>`:''}`;
}
function attendeesView(){if(workspace==='desk')return scanLogView();return `<section class="list-card"><div class="list-toolbar"><label class="search-field">${icon('search')}<input id="attendee-search" type="search" placeholder="Search name, company or ticket code" value="${esc(search)}" aria-label="Search attendees"></label><div class="filters" aria-label="Filter attendees">${[['all','Everyone'],['waiting','Not arrived'],['arrived','Checked in']].map(([v,l])=>`<button data-filter="${v}" class="${filter===v?'selected':''}" aria-pressed="${filter===v}">${l}</button>`).join('')}</div><button class="btn outline" id="export">${icon('download')}Export</button></div><div id="attendee-results">${attendeeRows()}</div></section>`}
function attendeeRows(){if(workspace==='desk')return scanLogRows();const rows=state.attendees.filter(a=>(filter==='all'||(filter==='arrived'?!!a.checkedIn:!a.checkedIn))&&`${a.name} ${a.email||''} ${a.company} ${a.id} ${(a.qrCodes||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase()));return `<div class="table-summary">${rows.length} attendees <span>${workspace==='desk'?'Registered guests only':'Demo guest list'}</span></div><div class="table-scroll"><table><thead><tr><th>ATTENDEE</th><th>TICKET</th><th>STATUS</th><th><span class="sr-only">Action</span></th></tr></thead><tbody>${rows.map(a=>`<tr><td><strong>${esc(a.name)}</strong><span>${esc(a.company)}</span>${a.email?`<span>${esc(a.email)}</span>`:''}</td><td>${a.type}<span>${a.id}${a.qrCodes?.length?' · Existing QR linked':''}</span></td><td><span class="status-badge ${a.checkedIn?'arrived':''}">${a.checkedIn?`${icon('check')} In at ${time(a.checkedIn)}`:'Not arrived'}</span></td><td><button class="btn ${a.checkedIn?'outline':'dark'} compact" data-attendee="${a.id}">${a.checkedIn?'View ticket':'Check in'} ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div>${!rows.length?'<div class="empty"><h3>No guests found</h3><p>Try a different name or ticket code.</p></div>':''}`}
function queueView(){return `<section class="list-card"><div class="card-heading"><h2>Needs a helping hand <span class="pill">${state.queue.length}</span></h2><span class="subtle">Staff follow-up</span></div>${state.queue.length?state.queue.map(q=>`<div class="queue-row"><span class="queue-warning">${icon('warning')}</span><div><h3>${esc(q.name)}</h3><p>${esc(q.reason)} · ${esc(q.ticket)} · ${time(q.time)}</p></div><button class="btn outline" data-resolve="${esc(q.ticket)}">Review ${icon('arrow')}</button></div>`).join(''):`<div class="empty"><div class="empty-mark">${icon('check')}</div><h3>No tickets to review.</h3><p>Tickets that need a closer look will appear here.<br>Keep scanning to record the next ticket.</p><button class="btn dark" data-view="checkin">Back to check-in ${icon('arrow')}</button></div>`}</section>`}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('.brand').onclick=e=>{e.preventDefault();navigate('checkin')};$('#start-camera')?.addEventListener('click',startCamera);$('#stop-camera')?.addEventListener('click',()=>{registering=false;stopCamera();render()});$('#upload-btn')?.addEventListener('click',()=>$('#qr-upload').click());$('#qr-upload').onchange=uploadQR;$('#qr-upload').oncancel=()=>{registering=false};$('#register-existing')?.addEventListener('click',registrationStart);$('#manual-btn')?.addEventListener('click',manualDialog);$('#sample-tickets')?.addEventListener('click',sampleTickets);document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>{const kind=b.dataset.demo;processTicket(kind==='success'?(state.attendees.find(a=>!a.checkedIn)?.id||'DIBI-0001'):kind==='duplicate'?'DIBI-0004':'DIBI-9999','Demo scan')});$('#attendee-search')?.addEventListener('input',e=>{search=e.target.value;$('#attendee-results').innerHTML=attendeeRows();bindRows()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});bindRows();$('#export')?.addEventListener('click',exportCsv);document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>reviewIssue(b.dataset.resolve));$('#modal').addEventListener('close',()=>{previousFocus?.focus()});}
function bindRows(){document.querySelectorAll('[data-attendee]').forEach(b=>b.onclick=()=>confirmGuest(b.dataset.attendee))}
function navigate(next){stopCamera();registering=false;view=next;render()}
function openDialog(html){stopCamera();previousFocus=document.activeElement;$('#modal').innerHTML=`<button class="dialog-close" aria-label="Close dialog">${icon('close')}</button>${html}`;$('#modal').setAttribute('aria-label',$('#modal h2')?.textContent||'Ticket details');$('#modal').classList.toggle('scan-result',Boolean($('#next-ticket')));$('#modal').showModal();$('.dialog-close').onclick=closeDialog;}
function closeDialog(){registering=false;$('#modal').close();if(view==='checkin')render()}
function processTicket(id,method='QR scan'){
 stopCamera();
 if(workspace==='desk'){
  registering=false;
  try{result=recordTicketScan(state,id,method);result.method=method;save();render();if(result.status==='shared'){sharedGuestLookup();return}showScanResult()}
  catch(err){render();toast(err.message)}
  return;
 }
 if(registering){registering=false;render();if((state.sharedQRCodes||[]).includes(id)){sharedGuestLookup();return}const existing=findAttendee(state,id);if(existing){confirmGuest(existing.id);return}registrationDialog(id);return}
 result=checkIn(state,id,method);result.method=method;save();render();if(result.status==='shared'){sharedGuestLookup();return}showResult()
}
function showResult(){const a=result.attendee, success=result.status==='success',duplicate=result.status==='duplicate';openDialog(`<div class="result ${success?'success':'problem'}"><div class="result-symbol">${icon(success?'check':'warning')}</div><span class="eyebrow">${success?'YOU’RE ON THE LIST':duplicate?'LET’S DOUBLE-CHECK':'A LITTLE HELP NEEDED'}</span><h2>${success?'You’re in. Welcome!':duplicate?'Already checked in':'Ticket not found'}</h2><p>${success?'Check-in recorded.':duplicate?`This ticket was checked in at ${time(a.checkedIn)}. Check the guest’s details before letting them through.`:'We couldn’t match this QR code to today’s guest list. Try a name search or ask the help desk.'}</p>${a?`<div class="guest-ticket"><span class="person-avatar">${esc(a.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span><div><h3>${esc(a.name)}</h3><p>${esc(a.company)} · ${a.type}</p><code>${a.id}</code></div></div>`:`<code class="unknown-code">${esc(result.id.slice(0,100))}</code>`}${success?`<div class="staff-action"><span class="small-label">YOUR NEXT STEP</span><p>Hand over their badge and point them towards the event.</p></div><button class="btn dark full" id="next-guest">Scan next guest ${icon('arrow')}</button>`:`<button class="btn dark full" id="find-guest">${icon('search')}Find attendee by name</button>${!duplicate?`<button class="btn outline full" id="register-scanned">Register this QR to a guest ${icon('arrow')}</button>`:''}<button class="btn outline full" id="send-help">Send to help queue ${icon('arrow')}</button><button class="text-btn centered" id="try-again">Try another ticket</button>`}</div>`);$('#next-guest')?.addEventListener('click',()=>{const resume=result.method==='QR scan';closeDialog();navigate('checkin');if(resume)startCamera()});$('#find-guest')?.addEventListener('click',()=>{closeDialog();navigate('attendees');$('#attendee-search').focus()});$('#register-scanned')?.addEventListener('click',()=>registrationDialog(result.id));$('#send-help')?.addEventListener('click',()=>{const added=addToQueue(state,result);save();closeDialog();render();toast(added?'Added to help queue. Direct the guest to the help desk.':'This ticket is already in the help queue.')});$('#try-again')?.addEventListener('click',()=>{closeDialog();navigate('checkin')})}
function manualDialog(){openDialog(`<div class="dialog-body"><span class="eyebrow">MANUAL CHECK-IN</span><h2>Enter ticket code.</h2><p>Enter the code printed below the guest’s QR code.</p><form id="ticket-form"><label for="ticket-code">Ticket code</label><input id="ticket-code" placeholder="e.g. DEMO-EB-001" required autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" enterkeyhint="go" maxlength="8192"><button class="btn dark full">Check ticket ${icon('arrow')}</button></form></div>`);$('#ticket-form').onsubmit=e=>{e.preventDefault();const id=$('#ticket-code').value.trim();if(id)processTicket(id,'Ticket code')};$('#ticket-code').focus()}
function confirmGuest(id){if(workspace==='desk'){ticketDetails(id);return}const a=state.attendees.find(a=>a.id===id);openDialog(`<div class="dialog-body"><span class="eyebrow">${a.checkedIn?'GUEST DETAILS':'STAFF CHECK-IN'}</span><h2>${esc(a.name)}</h2><p>${esc(a.company)} · ${a.type}</p><div class="info-box"><strong>${a.id}</strong><p>${a.checkedIn?`Checked in at ${time(a.checkedIn)}.`:'Confirm the guest’s name and ticket details, then check them in.'}</p>${a.email?`<p>${esc(a.email)}</p>`:''}</div>${workspace==='desk'?`<button class="btn outline full" id="edit-details">Edit guest details</button>`:''}<button class="btn dark full" id="confirm-checkin">${a.checkedIn?'Back to attendees':'Confirm check-in'} ${icon('arrow')}</button></div>`);$('#edit-details')?.addEventListener('click',()=>editGuestDetails(id));$('#confirm-checkin').onclick=()=>a.checkedIn?closeDialog():processTicket(id,'Staff check-in')}
function reviewIssue(ticket){const q=state.queue.find(q=>q.ticket===ticket);openDialog(`<div class="dialog-body"><span class="eyebrow">STAFF FOLLOW-UP</span><h2>${esc(q.name)}</h2><p>${esc(q.reason)} · ${esc(q.ticket)}</p><div class="info-box"><strong>Check before resolving</strong><p>${q.reason==='Already checked in'?'Confirm the guest’s identity and whether they are returning. Resolving this item will not add another check-in.':'Search the guest list and verify the booking. A matched guest can be checked in from their record. Resolving this item alone does not grant entry.'}</p></div><button class="btn dark full" id="queue-search">Find guest ${icon('search')}</button><button class="btn outline full" id="resolve-issue">Mark issue resolved ${icon('check')}</button></div>`);$('#queue-search').onclick=()=>{closeDialog();navigate('attendees')};$('#resolve-issue').onclick=()=>{state.queue=state.queue.filter(q=>q.ticket!==ticket);save();closeDialog();render();toast('Issue resolved. Attendance count unchanged.')}}
async function sampleTickets(){openDialog(`<div class="dialog-body"><span class="eyebrow">DEMO TICKETS</span><h2>Ready for a test scan.</h2><p>Scan from another screen, or download a QR and use “Upload QR image”.</p><div id="samples" class="samples"></div></div>`);for(const [id,label] of [['DIBI-0001','Alex Morgan'],['DIBI-0004','Already checked in'],['DIBI-9999','Unknown ticket']]){const url=await QRCode.toDataURL(id,{width:200,margin:4});if(!$('#samples'))return;$('#samples').insertAdjacentHTML('beforeend',`<a class="sample" href="${url}" download="${id}.png"><img src="${url}" alt="QR ticket ${id}"><strong>${label}</strong><span>${id} ${icon('download')}</span></a>`)}}
async function startCamera(){const generation=++cameraGeneration;$('#start-camera').disabled=true;$('#start-camera').textContent='Opening camera…';try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');const acquired=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280}},audio:false});if(generation!==cameraGeneration||view!=='checkin'){acquired.getTracks().forEach(t=>t.stop());return}stream=acquired;const video=$('#camera');video.srcObject=stream;await video.play();if(generation!==cameraGeneration)return;video.hidden=false;$('#scanner-content').hidden=true;$('#stop-camera').hidden=false;$('#camera-status').textContent='Camera on · ready to scan';const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let last=0;function tick(now){if(!stream||generation!==cameraGeneration)return;if(now-last>160&&video.readyState>=2&&video.videoWidth>0&&video.videoHeight>0){last=now;canvas.width=640;canvas.height=Math.round(video.videoHeight/video.videoWidth*640);ctx.drawImage(video,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);const code=jsQR(pixels.data,pixels.width,pixels.height);if(code?.data){processTicket(code.data);return}}frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick)}catch(err){if(generation!==cameraGeneration)return;registering=false;stopCamera();render();$('#camera-message').innerHTML=`<div class="camera-error">${icon('camera')}<span><strong>Camera unavailable.</strong> ${err.name==='NotAllowedError'?'Allow camera access in your browser, or use a ticket code.':'Try uploading a QR image or entering the ticket code.'}</span></div>`}}
function stopCamera(){cameraGeneration++;if(frame)cancelAnimationFrame(frame);stream?.getTracks().forEach(t=>t.stop());stream=null;frame=null}
async function uploadQR(event){const file=event.target.files[0];if(!file)return;stopCamera();try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);const code=jsQR(pixels.data,pixels.width,pixels.height);if(code?.data)processTicket(code.data,'QR image');else{registering=false;render();toast('No QR code found. Try a clearer image or enter the ticket code.')}}catch{registering=false;render();toast('Couldn’t read this image. Try a PNG or JPG.')}finally{if($('#qr-upload'))$('#qr-upload').value=''}}
function exportCsv(){const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv=[['Record ID','Ticket / QR','Name','Email','Company','Type','Checked in'],...state.attendees.map(a=>[a.id,(a.qrCodes||[]).join(' | '),a.name,a.email||'',a.company,a.type,a.checkedIn||''])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=workspace==='desk'?'dibi-ticket-scans.csv':'dibi-demo-attendees.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(workspace==='desk'?'Ticket scan log exported.':'Attendee list exported.')}
window.addEventListener('pagehide',stopCamera);document.addEventListener('visibilitychange',()=>{if(document.hidden&&stream){stopCamera();render()}});render();

function registrationStart(){
 openDialog(`<div class="dialog-body"><span class="eyebrow">USE YOUR EXISTING TICKETS</span><h2>Register an existing QR.</h2><p>Scan or upload the QR you already have, then link it to a guest. You can also paste its exact text or full booking URL.</p><button class="btn dark full" id="register-camera">${icon('camera')}Scan existing QR</button><button class="btn outline full" id="register-upload">${icon('upload')}Upload existing QR</button><form id="register-payload-form" class="registration-form"><label for="register-payload">QR text or URL</label><textarea id="register-payload" autocapitalize="none" autocorrect="off" spellcheck="false" rows="3" maxlength="8192" required placeholder="Paste exactly what your QR code contains"></textarea><button class="btn outline full">Continue ${icon('arrow')}</button></form></div>`);
 $('#register-camera').onclick=()=>{closeDialog();registering=true;$('#camera-status').textContent='Scan a QR to register';startCamera()};
 $('#register-upload').onclick=()=>{closeDialog();registering=true;$('#qr-upload').click()};
 $('#register-payload-form').onsubmit=e=>{e.preventDefault();const raw=$('#register-payload').value;registering=true;processTicket(raw)};
}
function registrationDialog(raw){
 openDialog(`<div class="dialog-body"><span class="eyebrow">EXISTING QR TICKET</span><h2>Who does this QR belong to?</h2><p>Confirm the guest’s booking before registering. Individual tickets link to one guest. A shared event QR opens guest lookup.</p><details class="payload-details"><summary>View scanned QR content</summary><code>${esc(raw)}</code></details><form id="register-guest-form" class="registration-form"><label for="qr-usage">How is this QR used?</label><select id="qr-usage"><option value="individual">Unique ticket for one attendee</option><option value="shared">Same event QR for everyone</option></select><div id="individual-registration"><label for="registration-mode">Guest record</label><select id="registration-mode"><option value="existing">Link to an existing attendee</option><option value="new">Add a new attendee</option></select><div id="existing-guest-fields"><label for="registration-search">Find attendee</label><input id="registration-search" type="search" placeholder="Search name, company or ticket code"><label for="registration-attendee">Select attendee</label><select id="registration-attendee" required></select></div><div id="new-guest-fields" hidden><label for="registration-name">Full name</label><input id="registration-name" autocomplete="name" maxlength="150"><label for="registration-company">Company (optional)</label><input id="registration-company" autocomplete="organization" maxlength="150"></div></div><p class="registration-error" id="registration-error" role="alert"></p><button class="btn dark full" type="submit" value="checkin" id="register-submit">Register & check in ${icon('check')}</button><button class="btn outline full" type="submit" value="save">Register for later</button></form></div>`);
 const fillOptions=()=>{const query=$('#registration-search').value.toLowerCase();const matches=state.attendees.filter(a=>`${a.name} ${a.company} ${a.id}`.toLowerCase().includes(query));$('#registration-attendee').innerHTML='<option value="">Choose a guest…</option>'+matches.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} — ${a.id}${a.checkedIn?' (already checked in)':''}</option>`).join('')};
 fillOptions();$('#registration-search').oninput=fillOptions;
 $('#qr-usage').onchange=()=>{const shared=$('#qr-usage').value==='shared';$('#individual-registration').hidden=shared;$('#registration-attendee').required=!shared&&$('#registration-mode').value==='existing';$('#registration-name').required=!shared&&$('#registration-mode').value==='new';$('#register-submit').textContent=shared?'Register & find guest':'Register & check in'};
 $('#registration-mode').onchange=()=>{const isNew=$('#registration-mode').value==='new';$('#existing-guest-fields').hidden=isNew;$('#new-guest-fields').hidden=!isNew;$('#registration-attendee').required=!isNew;$('#registration-name').required=isNew};
 $('#register-guest-form').onsubmit=e=>{e.preventDefault();const isNew=$('#registration-mode').value==='new';try{if($('#qr-usage').value==='shared'){registerSharedQR(state,raw);save();if(e.submitter?.value==='checkin'){closeDialog();render();sharedGuestLookup()}else{closeDialog();render();toast('Shared event QR registered. Scans will open guest lookup.')}return}const attendee=registerQR(state,raw,isNew?{name:$('#registration-name').value,company:$('#registration-company').value}:{attendeeId:$('#registration-attendee').value});save();if(e.submitter?.value==='checkin'){processTicket(raw,'Registered QR')}else{closeDialog();render();toast(`Existing QR registered to ${attendee.name}. Ready for check-in.`)}}catch(err){$('#registration-error').textContent=err.message}};
}

function sharedGuestLookup(){
 openDialog(`<div class="dialog-body"><span class="eyebrow">EVENT QR RECOGNISED</span><h2>${workspace==='desk'?'Use an individual ticket code':'Let’s find your guest.'}</h2><p>This QR is shared by everyone, so it cannot identify separate tickets. Enter the unique code printed on their ticket.</p><form id="shared-code-form"><label for="shared-ticket-code">Individual ticket code</label><input id="shared-ticket-code" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" enterkeyhint="go" required maxlength="8192" placeholder="e.g. DEMO-EB-001"><button class="btn dark full">Check ticket ${icon('arrow')}</button></form><button class="btn outline full" id="shared-search">${icon('search')}${workspace==='desk'?'Search scan log':'Find attendee by name'}</button></div>`);
 $('#shared-code-form').onsubmit=e=>{e.preventDefault();processTicket($('#shared-ticket-code').value.trim(),'Ticket code')};
 $('#shared-search').onclick=()=>{closeDialog();navigate('attendees');$('#attendee-search').focus()};
}

function guestDetailFields(guest={}) {
 return `<label for="desk-name">Full name <span class="field-required">Required</span></label><input id="desk-name" name="name" required maxlength="150" autocomplete="off" value="${esc(guest.detailsCollected===false?'':guest.name||'')}" placeholder="Ask for the guest’s full name"><label for="desk-email">Email (optional)</label><input id="desk-email" name="email" type="email" maxlength="254" autocomplete="off" value="${esc(guest.email||'')}" placeholder="guest@example.com"><label for="desk-company">Company (optional)</label><input id="desk-company" name="company" maxlength="150" autocomplete="off" value="${esc(guest.company||'')}" placeholder="Company or organisation">`;
}
function editGuestDetails(id){
 const guest=state.attendees.find(a=>a.id===id);
 openDialog(`<div class="dialog-body"><span class="eyebrow">GUEST DETAILS</span><h2>Edit guest details</h2><p>Update their record. Their ticket and check-in status stay the same.</p><form id="edit-guest-form">${guestDetailFields(guest)}<p class="registration-error" id="edit-guest-error" role="alert"></p><button class="btn dark full">Save details ${icon('check')}</button></form></div>`);
 $('#edit-guest-form').onsubmit=e=>{e.preventDefault();try{updateGuestDetails(state,id,{name:$('#desk-name').value,email:$('#desk-email').value,company:$('#desk-company').value});save();closeDialog();render();toast('Guest details updated.')}catch(err){$('#edit-guest-error').textContent=err.message}};
}

function showScanResult(){
 const a=result.attendee,success=result.status==='success';
 openDialog(`<div class="result ${success?'success':'problem'}"><div class="result-symbol">${icon(success?'check':'warning')}</div><span class="eyebrow">${success?'RECORDED':'DUPLICATE SCAN'}</span><h2>${success?'Ticket scanned':'Already scanned'}</h2><p>${success?'Recorded. Ready for the next ticket.':`First scanned at ${time(a.checkedIn)}. It hasn’t been counted again.`}</p><div class="scan-receipt"><span class="small-label">TICKET / QR CODE</span><code>${esc(a.qrCodes?.[0]||a.id)}</code><span>Recorded at ${time(a.checkedIn)}</span>${a.detailsCollected?`<strong>${esc(a.name)}</strong>`:''}</div></div><div class="modal-actions"><button class="btn dark full" id="next-ticket">Scan next ticket ${icon('arrow')}</button>${!success?`<button class="btn outline full" id="scan-help">Send to help queue</button>`:''}<button class="text-btn centered" id="open-scan-log">View scan log</button></div>`);
 $('#next-ticket').onclick=()=>{const resume=result.method==='QR scan';closeDialog();navigate('checkin');if(resume)startCamera()};
 $('#open-scan-log').onclick=()=>{closeDialog();navigate('attendees')};
 $('#scan-help')?.addEventListener('click',()=>{addToQueue(state,result);save();closeDialog();render();toast('Duplicate ticket added to the help queue.')});
}
function scanLogView(){
 return `<section class="list-card"><div class="list-toolbar"><label class="search-field">${icon('search')}<input id="attendee-search" type="search" placeholder="Search ticket or QR code" value="${esc(search)}" aria-label="Search scan log"></label><button class="btn outline" id="export">${icon('download')}Export</button></div><div id="attendee-results">${scanLogRows()}</div></section>`;
}
function scanLogRows(){
 const rows=state.attendees.filter(a=>`${a.name} ${a.email||''} ${a.company} ${a.id} ${(a.qrCodes||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 rows.sort((a,b)=>(b.checkedIn||'').localeCompare(a.checkedIn||''));
 return `<div class="table-summary">${rows.length} ${rows.length===1?'ticket':'tickets'} <span>Recorded in this browser</span></div>${rows.length?`<div class="table-scroll"><table class="scan-log-table"><thead><tr><th>TICKET / QR CODE</th><th>FIRST SCANNED</th><th>STATUS</th><th><span class="sr-only">Action</span></th></tr></thead><tbody>${rows.map(a=>`<tr><td><code class="ticket-code-cell">${esc(a.qrCodes?.[0]||a.id)}</code>${a.detailsCollected?`<span>${esc(a.name)}</span>`:''}</td><td><span class="mobile-cell-label">First scanned</span>${a.checkedIn?time(a.checkedIn):'—'}</td><td><span class="status-badge ${a.checkedIn?'arrived':''}">${a.checkedIn?`${icon('check')} Scanned`:'Not scanned'}</span></td><td><button class="btn outline compact" data-attendee="${a.id}">View ticket ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h3>No tickets found.</h3><p>Scan a ticket or try a different code.</p></div>'}`;
}
function ticketDetails(id){
 const a=state.attendees.find(a=>a.id===id);
 openDialog(`<div class="dialog-body"><span class="eyebrow">TICKET RECORD</span><h2>${a.checkedIn?'Ticket scanned':'Not scanned yet'}</h2><div class="scan-receipt"><span class="small-label">TICKET / QR CODE</span>${(a.qrCodes?.length?a.qrCodes:[a.id]).map(code=>`<code>${esc(code)}</code>`).join('')}<span>${a.checkedIn?`First scanned at ${time(a.checkedIn)}`:'No scan recorded'}</span></div>${a.detailsCollected?`<div class="info-box"><strong>${esc(a.name)}</strong><p>${esc(a.email||'')}</p><p>${esc(a.company||'')}</p></div>`:''}<button class="btn dark full" id="ticket-detail-primary">${a.checkedIn?'Back to scan log':'Mark as scanned'} ${icon(a.checkedIn?'arrow':'check')}</button><button class="text-btn centered" id="ticket-detail-edit">${a.detailsCollected?'Edit guest details':'Add guest details (optional)'}</button></div>`);
 $('#ticket-detail-primary').onclick=()=>a.checkedIn?closeDialog():processTicket(a.qrCodes?.[0]||a.id,'Staff action');
 $('#ticket-detail-edit').onclick=()=>editGuestDetails(id);
}

// Keep ticket actions inside the visible screen when the phone keyboard opens.
function syncVisualViewport(){
 const viewport=window.visualViewport;
 document.documentElement.style.setProperty('--viewport-height',`${viewport?.height||window.innerHeight}px`);
 document.documentElement.style.setProperty('--viewport-top',`${viewport?.offsetTop||0}px`);
}
window.visualViewport?.addEventListener('resize',syncVisualViewport);
window.visualViewport?.addEventListener('scroll',syncVisualViewport);
window.addEventListener('resize',syncVisualViewport);
syncVisualViewport();
